-- Basic config
require("core.lazy")
require("core.mappings")
require("core.configs")

-- Plugins setting
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.neotree")
require("plugins.cmp")
require("plugins.mason")
require("plugins.mason-lspconfig")
require("plugins.mason-nvim-dap")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.colorizer")
require("plugins.toggleterm")
require("plugins.java")
require("plugins.lspconfig")
require("plugins.jdtls")
require("plugins.move")
require("plugins.dashboard")
require("plugins.comment")
require("plugins.nvim-notify")
require("plugins.lspsaga")
require("plugins.indent")
--require("plugins.mini-indentscope")  --FIX: The problem with the dashboard plugin
require("plugins.gitsigns")
require("plugins.which-key")            -- TODO: add description for main mappings
require("plugins.trouble")
require("plugins.surround")             --TODO: change config
require("plugins.dap")
require("plugins.dap-ui")
require("plugins.dap-virtual-text")
require("plugins.emoji")
require("plugins.nerdy")
require("plugins.web-tools")
require("plugins.colortils")
require("plugins.sqls")
require("plugins.noice")
