-- Basic config
require("core.configs")
require("core.lazy")
require("core.mappings")

-- Plugins settings
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.neotree")
require("plugins.cmp")
require("plugins.mason")
require("plugins.mason-lspconfig")
require("plugins.mason-nvim-dap")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.colorizer")
require("plugins.toggleterm")
require("plugins.java")
require("plugins.lspconfig")
require("plugins.jdtls")
require("plugins.move")
require("plugins.dashboard")
require("plugins.comment")
