return {
  "RRethy/vim-illuminate",
  event = "BufReadPost",
  config = function()
    require("illuminate").configure({
      providers = {
        "lsp",
        "treesitter",
      },
      delay = 1000,
      filetype_overrides = {},
      filetypes_denylist = {
        "lube",
        "TelescopeResults",
        "query",
        "gitrebase",
        "gitcommit",
        "tsplayground",
        "lazy",
        "lsp-installer",
        "markdown",
        "mason",
        "text",
        "dashboard",
        "alpha",
        "NvimTree",
        "undotree",
        "diff",
        "fugitive",
        "fugitiveblame",
        "Outline",
        "SidebarNvim",
        "packer",
        "lsp-installer",
        "TelescopePrompt",
        "help",
        "telescope",
        "lspinfo",
        "Trouble",
        "null-ls-info",
        "quickfix",
        "chadtree",
        "fzf",
        "NeogitStatus",
        "terminal",
        "console",
        "term://*",
        "Term://*",
        "toggleterm",
        "qf",
        "prompt",
        "noice",
        "",
      },
      filetypes_allowlist = {},
      modes_denylist = {},
      modes_allowlist = {},
      providers_regex_syntax_denylist = {},
      providers_regex_syntax_allowlist = {},
      under_cursor = true,
      large_file_cutoff = 5000,
      large_file_overrides = {
        providers = { "lsp" },
      },
      min_count_to_highlight = 2,
    })
  end
}
